version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"  # Пробрасываем порт Flask
    volumes:
      - .:/app  # Привязываем локальные файлы к контейнеру
    environment:
      - FLASK_ENV=development  # Для отладки приложения
